[project]
name = "mlops-capstone"
version = "0.0.1"
description = "Capstone project for mlops-zoomcamp. Analysis on Singapore's Educational + Healthcare spending vs GDP growth."
authors = ["Ella Sahnan <ellacharmed@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
repository = "https://github.com/prefix-dev/pixi"

[tasks]

[pypi-dependencies]
pandas = ">=2.2.2,<2.3"
numpy = ">=1.26.4,<1.27"
scikit-learn = ">=1.5.1,<1.6"

[dependencies]
requests = ">=2.32.3,<2.33"


[feature.python.dependencies]
python = "3.11.*"

[feature.py39.dependencies]
python = "~=3.9.0"
[feature.py310.dependencies]
python = "~=3.10.0"

[feature.test.dependencies]
pytest = "*"

[feature.lint.dependencies]
pre-commit = "*"

[feature.dev.dependencies]
altair = ">=5.3.0,<5.4"
ydata-profiling = "*"
scikit-learn-intelex = ">=2024.3.0,<2024.4"
mlflow = ">=2.14.2,<2.15"
evidently = ">=0.4.30,<0.5"
pip = ">=24.0,<25"
ipykernel = ">=6.29.5,<6.30"
ipywidgets = ">=8.1.3,<8.2"

[feature.test.tasks]
test = "pytest"

[environments]
# implicit: default = ["default"]
# Change to "python" as you are using Python 3.11
default = ["python", "lint"] 
test = ["test"] # implicit: test = ["test", "default"]
py39 = ["py39"] # implicit: py39 = ["py39", "default"]
test39 = ["test", "py39"] # implicit: test39 = ["test", "py39", "default"]
py310 = ["py310"] # implicit: py310 = ["py310", "default"]
test310 = ["test", "py310"] # implicit: test310 = ["test", "py310", "default"]
dev = ["dev", "python", "lint", "test"]

